apiVersion: v1
kind: Pod
metadata:
  labels:
    project: jenkins-global-lib
    imagetype: ubuntu
spec:
  containers:
  - name: my-ubuntu-container
    image: ubuntu
    command:
    - cat
    tty: true